name: form_field_controller_example
description: Demonstrates how to use the form_field_controller plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  form_field_controller:
    path: ../
  cupertino_icons: ^1.0.2
  annotations:
    path: ../annotations

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  generators:
    path: ../generators


flutter:
  uses-material-design: true
